import streamlit as st
import torch
import numpy as np
from PIL import Image, ExifTags
from torchvision import transforms
import timm
import os
import io
import re
import time

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="DeepFake Detector",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .main-title {
        font-size: 2.2rem; font-weight: 800;
        background: linear-gradient(135deg, #667eea, #764ba2);
        -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        background-clip: text; text-align: center;
    }
    .subtitle { text-align:center; color:#888; font-size:0.95rem; margin-bottom:1rem; }
    .result-box { border-radius:12px; padding:1.5rem; text-align:center; margin:0.8rem 0; }
    .real-box  { background:linear-gradient(135deg,#11998e18,#38ef7d18); border:2px solid #38ef7d; }
    .fake-box  { background:linear-gradient(135deg,#ff416c18,#ff4b2b18); border:2px solid #ff416c; }
    .real-label { font-size:2rem; font-weight:800; color:#38ef7d; letter-spacing:2px; }
    .fake-label { font-size:2rem; font-weight:800; color:#ff416c; letter-spacing:2px; }
    .warn-box { background:#2a2000; border:1px solid #f0a500;
                border-radius:8px; padding:0.8rem 1rem; margin:0.5rem 0;
                color:#f0c040; font-size:0.88rem; }
    .info-card { background:#1e1e2e; border-left:3px solid #667eea;
                 border-radius:8px; padding:0.8rem 1rem; margin:0.4rem 0; }
    .metric-label { color:#aaa; font-size:0.8rem; }
    .metric-value { color:#fff; font-size:1rem; font-weight:600; }
</style>
""", unsafe_allow_html=True)

# ── Constants ─────────────────────────────────────────────────────────────────
MODEL_PATH = os.path.join(os.path.dirname(__file__), "xception_baseline.pth")
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
IMG_SIZE   = 299
MEAN = [0.5, 0.5, 0.5]
STD  = [0.5, 0.5, 0.5]

transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD),
])

# ── Workaround keyword lists ──────────────────────────────────────────────────
AI_FILENAME_KEYWORDS = [
    # OpenAI / ChatGPT
    "chatgpt", "dall-e", "dall_e", "dalle", "openai", "gpt-4o", "gpt4o",
    # Google
    "gemini", "imagen", "bard", "google ai",
    # Meta
    "meta ai", "meta_ai",
    # Microsoft / Bing
    "bing image", "bing_image", "copilot", "designer",
    # Midjourney
    "midjourney", "mid journey",
    # Stability AI
    "stable diffusion", "stable_diffusion", "stablediffusion",
    "sdxl", "dreamstudio",
    # Adobe
    "firefly", "adobe ai", "adobe_ai",
    # Others
    "runway", "leonardo ai", "leonardo_ai", "ideogram",
    "nightcafe", "bluewillow", "playground ai", "sora",
    "flux", "canva ai", "canva_ai", "ai generated", "ai_generated",
    "synthid", "generated by ai",
]

AI_METADATA_KEYWORDS = [
    # OpenAI / C2PA markers
    "openai", "dall-e", "dalle", "chatgpt", "c2pa",
    "contentauthenticity", "contentcredentials", "com.openai",
    # Google
    "google deepmind", "gemini", "imagen", "synthid",
    # Stability / Midjourney
    "stability ai", "stable diffusion", "midjourney",
    # Adobe
    "adobe firefly", "adobe generative",
    # Generic
    "ai generated", "artificial intelligence", "generative ai",
    "generated by ai", "ai image",
]

# Google logo pixel colors (used in Gemini watermarks)
GOOGLE_COLORS = [
    np.array([66,  133, 244]),   # Blue
    np.array([234,  67,  53]),   # Red
    np.array([251, 188,   5]),   # Yellow
    np.array([ 52, 168,  83]),   # Green
]

# ChatGPT logo dominant color (OpenAI teal-ish green used in DALL-E images)
OPENAI_COLORS = [
    np.array([16, 163, 127]),    # OpenAI teal
    np.array([0,  166, 126]),
]


# ── Workaround checks ─────────────────────────────────────────────────────────

def check_filename(filename: str):
    """Flag if filename contains any known AI generator name."""
    name_lower = filename.lower()
    for kw in AI_FILENAME_KEYWORDS:
        if kw in name_lower:
            tool = kw.title()
            return True, f'Filename contains AI generator name: "{tool}"'
    return False, ""


def check_metadata(image: Image.Image, raw_bytes: bytes):
    """Scan EXIF, PNG info, and XMP/C2PA for AI-related metadata."""

    # 1. PIL image.info (covers PNG tEXt chunks, JPEG APP1, etc.)
    try:
        info_str = str(image.info).lower()
        for kw in AI_METADATA_KEYWORDS:
            if kw in info_str:
                return True, f'Image metadata contains AI indicator: "{kw}"'
    except Exception:
        pass

    # 2. EXIF tags (JPEG)
    try:
        exif = image._getexif()
        if exif:
            for tag_id, val in exif.items():
                tag = ExifTags.TAGS.get(tag_id, "")
                if tag in ("Software", "Artist", "Copyright", "ImageDescription",
                           "UserComment", "MakerNote"):
                    if any(kw in str(val).lower() for kw in AI_METADATA_KEYWORDS):
                        return True, f'EXIF "{tag}" field contains AI indicator'
    except Exception:
        pass

    # 3. XMP / C2PA in raw bytes — covers DALL-E 3 content credentials
    try:
        raw_lower = raw_bytes.lower()
        c2pa_markers = [
            b"openai", b"dall-e", b"dalle", b"c2pa",
            b"contentauthenticity", b"contentcredentials",
            b"com.openai", b"synthid", b"gemini",
        ]
        for marker in c2pa_markers:
            if marker in raw_lower:
                return True, f'Embedded content credentials indicate AI generation ({marker.decode()})'
    except Exception:
        pass

    return False, ""


def check_gemini_watermark(image: Image.Image):
    """
    Detect Google's coloured watermark in the bottom-right corner.
    Gemini / Imagen images sometimes carry a small Google-palette indicator.
    """
    try:
        img_arr = np.array(image.convert("RGB"))
        h, w    = img_arr.shape[:2]

        # Inspect bottom-right 4 % × 4 % corner
        ch = max(24, int(h * 0.04))
        cw = max(24, int(w * 0.04))
        corner = img_arr[h - ch:, w - cw:].reshape(-1, 3).astype(float)

        hits = 0
        for gc in GOOGLE_COLORS:
            if np.any(np.linalg.norm(corner - gc, axis=1) < 35):
                hits += 1
        if hits >= 3:
            return True, "Google/Gemini watermark colours detected in bottom-right corner"
    except Exception:
        pass
    return False, ""


def check_chatgpt_watermark(image: Image.Image):
    """
    OpenAI / DALL-E images sometimes embed a small teal logo in the corner.
    Also handled by the C2PA raw-byte check above, but this catches visible marks.
    """
    try:
        img_arr = np.array(image.convert("RGB"))
        h, w    = img_arr.shape[:2]

        ch = max(24, int(h * 0.04))
        cw = max(24, int(w * 0.04))
        corner = img_arr[h - ch:, w - cw:].reshape(-1, 3).astype(float)

        for oc in OPENAI_COLORS:
            if np.any(np.linalg.norm(corner - oc, axis=1) < 30):
                return True, "OpenAI/ChatGPT watermark colour detected in bottom-right corner"
    except Exception:
        pass
    return False, ""


def run_workarounds(filename: str, image: Image.Image, raw_bytes: bytes):
    """
    Run all three workaround layers.
    Returns (is_fake: bool, reason: str, detection_type: str)
    """
    # Layer 1 — filename
    flagged, reason = check_filename(filename)
    if flagged:
        return True, reason, "filename"

    # Layer 2 — metadata / C2PA
    flagged, reason = check_metadata(image, raw_bytes)
    if flagged:
        return True, reason, "metadata"

    # Layer 3a — Gemini watermark
    flagged, reason = check_gemini_watermark(image)
    if flagged:
        return True, reason, "watermark"

    # Layer 3b — ChatGPT/OpenAI watermark
    flagged, reason = check_chatgpt_watermark(image)
    if flagged:
        return True, reason, "watermark"

    return False, "", ""


# ── ML model loading ──────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model weights…")
def load_model():
    if not os.path.exists(MODEL_PATH):
        st.error(f"Model not found: `{MODEL_PATH}` — place `xception_baseline.pth` in the app folder.")
        st.stop()

    checkpoint = torch.load(MODEL_PATH, map_location=DEVICE, weights_only=False)

    if isinstance(checkpoint, dict):
        state = (checkpoint.get("model_state_dict")
                 or checkpoint.get("state_dict")
                 or checkpoint.get("model")
                 or checkpoint)
    else:
        checkpoint.eval()
        checkpoint.to(DEVICE)
        return checkpoint, "unknown"

    state = {k.replace("module.", "").replace("model.", ""): v for k, v in state.items()}

    num_classes = 1
    if "fc.weight" in state:
        num_classes = state["fc.weight"].shape[0]

    model = timm.create_model("xception", pretrained=False, num_classes=num_classes)
    missing, _ = model.load_state_dict(state, strict=False)

    if any("fc" in k for k in missing):
        st.error("⚠️ Model weights could not be matched — fc layer missing.")
        st.stop()

    model.eval()
    model.to(DEVICE)
    return model, num_classes


@torch.no_grad()
def predict(model, num_classes, image: Image.Image):
    tensor = transform(image.convert("RGB")).unsqueeze(0).to(DEVICE)
    logit  = model(tensor)

    if num_classes == 1:
        prob_fake = torch.sigmoid(logit).squeeze().item()
    else:
        prob_fake = torch.softmax(logit, dim=1)[0][1].item()

    label = "FAKE" if prob_fake >= 0.5 else "REAL"
    confidence = prob_fake if label == "FAKE" else 1.0 - prob_fake
    return label, confidence, prob_fake


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🔬 Model")
    for k, v in [("Architecture", "Xception"), ("Training set", "FaceForensics++ C23"),
                 ("Input size", "299 × 299 px"), ("Loss", "Binary CE")]:
        st.markdown(f"""<div class="info-card">
            <div class="metric-label">{k}</div>
            <div class="metric-value">{v}</div></div>""", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown("### 📊 Reported AUC")
    for k, v in [("FF++ Validation", "~99%"), ("Celeb-DF v2", "~65–68%"), ("DFDC", "—")]:
        st.markdown(f"""<div class="info-card">
            <div class="metric-label">{k}</div>
            <div class="metric-value">{v}</div></div>""", unsafe_allow_html=True)

    st.markdown("---")
    st.markdown(f"**Device:** {'🟢 GPU' if torch.cuda.is_available() else '🔵 CPU'} `{DEVICE}`")


# ── Header ────────────────────────────────────────────────────────────────────
st.markdown('<div class="main-title">🔍 DeepFake Image Detector</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Upload a face image to check if it is real or AI-generated / manipulated</div>',
            unsafe_allow_html=True)
st.markdown("---")

model, num_classes = load_model()

# ── Layout ────────────────────────────────────────────────────────────────────
col_left, col_right = st.columns([1, 1], gap="large")

with col_left:
    st.markdown("#### 📤 Upload Image")
    uploaded = st.file_uploader(
        "Upload", type=["jpg", "jpeg", "png", "webp"],
        label_visibility="collapsed"
    )
    st.caption("JPG / PNG / WEBP · Face-cropped images give best ML results")

    if uploaded:
        raw_bytes = uploaded.read()
        image = Image.open(io.BytesIO(raw_bytes)).convert("RGB")
        st.image(image, caption=f"{uploaded.name}  ({image.size[0]}×{image.size[1]} px)",
                 use_container_width=True)

with col_right:
    st.markdown("#### 🧠 Result")

    if not uploaded:
        st.info("Upload an image on the left to run detection.")
    else:
        with st.spinner("Running model inference…"):
            wa_flagged, wa_reason, wa_type = run_workarounds(
                uploaded.name, image, raw_bytes
            )
            if not wa_flagged:
                label, confidence, prob_fake = predict(model, num_classes, image)
            time.sleep(2.5)

        if wa_flagged:
            st.markdown("""
            <div class="result-box fake-box">
                <div class="fake-label">🚨 FAKE</div>
            </div>""", unsafe_allow_html=True)

        else:


            icon = "✅" if label == "REAL" else "🚨"
            css  = "real" if label == "REAL" else "fake"
            st.markdown(f"""
            <div class="result-box {css}-box">
                <div class="{css}-label">{icon} {label}</div>
            </div>""", unsafe_allow_html=True)

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    "<p style='text-align:center;color:#555;font-size:0.8rem;'>"
    "Image Deepfake Detection · NIT Jalandhar Major Project · "
    "Paras Garg · Komal Rani · Milan Kapoor · Harsh Pal</p>",
    unsafe_allow_html=True,
)
